3) A função é: c, A função é: d e por último A função é: a

4) sim, o await não tem que estar quando for chamar o c() e o d(), pois não é uma função async; 
outro erro é na função c e d, o alertUser('c') e o alertUser('d') resolvia as promisses então o certo é colocar eles dentro do resolve;
a função b alertUser('b') é inútil na função b;
o código poderia ter seguido o cleanCode